from __future__ import annotations

from app.models import MarketSnapshot, utc_now_iso


def demo_markets() -> list[MarketSnapshot]:
    observed_at = utc_now_iso()
    return [
        MarketSnapshot(
            platform="demo",
            market_id="demo-fed-cut",
            event_id="fed-policy",
            title="Will the Federal Reserve cut interest rates by September?",
            url="",
            category="rates",
            probability=0.58,
            yes_bid=0.57,
            yes_ask=0.59,
            volume=2_450_000,
            open_interest=1_350_000,
            liquidity=420_000,
            observed_at=observed_at,
            change_24h=-0.07,
            change_7d=-0.13,
        ),
        MarketSnapshot(
            platform="demo",
            market_id="demo-cpi-hot",
            event_id="inflation",
            title="Will next US CPI inflation print above consensus?",
            url="",
            category="inflation",
            probability=0.47,
            yes_bid=0.45,
            yes_ask=0.49,
            volume=930_000,
            open_interest=520_000,
            liquidity=210_000,
            observed_at=observed_at,
            change_24h=0.09,
            change_7d=0.16,
        ),
        MarketSnapshot(
            platform="demo",
            market_id="demo-oil",
            event_id="oil-shock",
            title="Will Brent crude oil trade above $90 this quarter?",
            url="",
            category="energy",
            probability=0.34,
            yes_bid=0.32,
            yes_ask=0.36,
            volume=615_000,
            open_interest=290_000,
            liquidity=120_000,
            observed_at=observed_at,
            change_24h=0.06,
            change_7d=0.11,
        ),
        MarketSnapshot(
            platform="demo",
            market_id="demo-geopolitics",
            event_id="geopolitical-risk",
            title="Will a major Russia-Ukraine ceasefire agreement be announced this month?",
            url="",
            category="geopolitics",
            probability=0.29,
            yes_bid=0.27,
            yes_ask=0.31,
            volume=1_100_000,
            open_interest=680_000,
            liquidity=180_000,
            observed_at=observed_at,
            change_24h=-0.04,
            change_7d=-0.08,
        ),
        MarketSnapshot(
            platform="demo",
            market_id="demo-ai-reg",
            event_id="ai-regulation",
            title="Will the US announce major AI regulation before year end?",
            url="",
            category="tech",
            probability=0.52,
            yes_bid=0.50,
            yes_ask=0.54,
            volume=780_000,
            open_interest=330_000,
            liquidity=150_000,
            observed_at=observed_at,
            change_24h=0.05,
            change_7d=0.07,
        ),
        MarketSnapshot(
            platform="demo",
            market_id="demo-btc",
            event_id="crypto-risk",
            title="Will Bitcoin trade above $120,000 before July?",
            url="",
            category="crypto",
            probability=0.41,
            yes_bid=0.40,
            yes_ask=0.43,
            volume=3_400_000,
            open_interest=1_900_000,
            liquidity=510_000,
            observed_at=observed_at,
            change_24h=0.08,
            change_7d=0.19,
        ),
        MarketSnapshot(
            platform="demo",
            market_id="demo-election",
            event_id="policy-risk",
            title="Will new US tariff policy be announced this quarter?",
            url="",
            category="politics",
            probability=0.63,
            yes_bid=0.61,
            yes_ask=0.65,
            volume=1_760_000,
            open_interest=890_000,
            liquidity=260_000,
            observed_at=observed_at,
            change_24h=0.03,
            change_7d=0.09,
        ),
        MarketSnapshot(
            platform="demo",
            market_id="demo-recession",
            event_id="growth-risk",
            title="Will the US enter a recession this year?",
            url="",
            category="growth",
            probability=0.22,
            yes_bid=0.21,
            yes_ask=0.24,
            volume=1_250_000,
            open_interest=770_000,
            liquidity=240_000,
            observed_at=observed_at,
            change_24h=0.02,
            change_7d=0.04,
        ),
    ]

